# Generated by Django 5.0.6 on 2024-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=224)),
                ('description', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
