# Generated by Django 5.0.6 on 2024-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=224)),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
            ],
        ),
    ]
