# Generated by Django 5.0.6 on 2024-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='code',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
